version: "3.3"

services:

  dama-db:
    container_name: "dama-db"
    image: mysql:latest
    volumes:
      - type: volume
        source: dama-volume
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: dama

  service-1:
    container_name: "service-1"
    image: mariuscsaunders/service-1
    build: ./service_1
    environment: 
      DATABASE_URI: "mysql+pymysql://root:pass@dama-db:3306/dama"
    restart: on-failure
    #deploy:
    #  replicas: 2
    
  service-2:
    container_name: "service-2"
    image: mariuscsaunders/service-2
    build: ./service_2
    #deploy:
    #  replicas: 2
  
  service-3:
    container_name: "service-3"
    image: mariuscsaunders/service-3
    build: ./service_3
    #deploy:
    #  replicas: 2

  service-4:
    container_name: "service-4"
    image: mariuscsaunders/service-4
    build: ./service_4
    #deploy:
    #  replicas: 2

  #Nginx reverse proxy
  dama-proxy:
    container_name: dama-proxy
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - service-1

volumes:
  dama-volume:
